### ISSUE TITLE
 Refactoring suggestion

### ISSUE THREAD

**Issue by Duduxs** [SirBergue/PyCraft#3]
Before everything, congratulations 4 this project, i like alot games creation.

I'd like to make a PR with suggestion in the Launcher.py. The changes are:

- Both Fade in Time and Fade Out Time:  Time reduced 2.5 to 1
- System fonts: Serif font to Comic Sans MS
- a readme

**Comment by SirBergue** [comment]
First of all, thanks for your help, @Duduxs ! I really appreciate it. Your README is awesome, and the comic sans font just fit very well.
The Fade Out Time I would already decrease it, since the compilation time is fast enough, so your changes will be merged.
